### ISSUE TITLE
npm run start就报错

### ISSUE THREAD

**Issue by Code-RoadFly** [546200350/vue-apicloud-webpack#1]
你这个能本地调试吗？能给个详细点的运行步骤吗，我这边到npm run start就报错了

**Comment by 546200350** [comment]
依赖包安装了么? 请帖一下错误代码

**Comment by a0921313520** [comment]
作者你好,运行就报错呢 

clean-webpack-plugin: C:\Users\Administrator\Desktop\vue-apicloud-webpack-master\dist\* is outside ot root. Skipping...
 94% asset optimization[copy-webpack-plugin] WARNING - unable to locate 'C:\Users\Administrator\Deskloud-webpack-master\static' at 'C:\Users\Administrator\Desktop\vue-apicloud-webpack-maste 95% emittiiled to compile with 1 errors13:15:52

**Comment by 546200350** [comment]
@a0921313520 请删除dist目录,重新运行

**Comment by 546200350** [comment]
@Code-RoadFly @a0921313520 项目结构重新调整了一下,稍后会更新RM文档
